# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 1

# Personal info
name: Fasih Zulfiqar
title: Data Analyst
email: fasih178@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: ZulfiqarFasih
github_username:  FasihZ
instagram_username: fasihz
linkedin_username: fasihz
youtube_username: fasihzulfiqar2015

additional_links:
- title: Blog
  icon: fa-brands fa-blogger
  url: https://pakonomist.wordpress.com

# About Section
# about_title: About Me
about_profile_image: https://media.licdn.com/dms/image/D4E03AQGpx43JyXJQ1Q/profile-displayphoto-shrink_400_400/0/1689577305057?e=1697068800&v=beta&t=Saw9AyMCIeNlcXv8GzizJ1D5RmGZsiVg_YkoRE8tnSI
about_content: | # this will include new lines to allow paragraphs
  I’m a client success manager at Trademor x Alibaba, a writing consultant at the Academic Writing Center at IBA, and a Teacher Assistant. I'm doing my Bachelor's of Science in ***Econ & Math at IBA***, Karachi, with a ***3.91 CGPA***. I'm also the CFO of the ***Animal Welfare Society*** at IBA.  
    
  Having ***self-studied*** for my A-levels and secondary education due to financial constraints, I'm also a proud autodidact. A distinction holder in A-level Economics in Pakistan and was awarded a scholarship by Professor Tyler Cowen, Mercatus Center, to pursue Economics.   
    
  I ruminate on all sorts of weird things at my blog Pakonomist. I've also done multiple projects of model optimization on R and Excel. Aside from academics and work, I invest and powerlift. Also a big football fan and was part of a club, GSA, for 6 years. Super into travelling and Philosophy, particularly Stoicism and Absurdism. And dogs. I love dogs.

  <i class="fas fa-plane"></i> <mark>Why travelling?</mark> I love to travel because it allows you to be in cultures much different than yours. Plus I love tasting new foods :D

  <i class="fas fa-dumbbell"></i> <mark>Why Powerlifting?</mark> Helps me push myself to new limits. When you have 250 lbs on your back and you squat down, there is always a chance you will fail. Your knees might strain, or worse, break. Conquering that fear is why I love powerlifting.

# About Section
# about_title: Education
about_profile_image: https://media.licdn.com/dms/image/D4E03AQGpx43JyXJQ1Q/profile-displayphoto-shrink_400_400/0/1689577305057?e=1697068800&v=beta&t=Saw9AyMCIeNlcXv8GzizJ1D5RmGZsiVg_YkoRE8tnSI
about_content: | # this will include new lines to allow paragraphs
  I'm doing my Bachelor's of Science in ***Econ & Math at IBA***, Karachi, with a ***3.91 CGPA***. I'm also the CFO of the ***Animal Welfare Society*** at IBA.  
    
  Having ***self-studied*** for my A-levels and secondary education due to financial constraints, I'm also a proud autodidact. A distinction holder in A-level Economics in Pakistan and was awarded a scholarship by Professor Tyler Cowen, Mercatus Center, to pursue Economics.   
    
  <i class="fas fa-plane"></i> <mark>Why travelling?</mark> I love to travel because it allows you to be in cultures much different than yours. Plus I love tasting new foods :D

  <i class="fas fa-dumbbell"></i> <mark>Why Powerlifting?</mark> Helps me push myself to new limits. When you have 250 lbs on your back and you squat down, there is always a chance you will fail. Your knees might strain, or worse, break. Conquering that fear is why I love powerlifting.


# Experience Section
experience_title: Last Experiences

# Projects Section
projects_title: Personal Projects

#Education Section
#educaton_title: Education

# Footer
footer_show_references: false

# Slider Settings
slider_settings:
  enabled: true
  loop: true
  auto: true
  speed: 800
  pause: 3000

# Build settings
remote_theme: nbentoneves/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
