# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 1

# Personal info
name: Fasih Zulfiqar
title: Data Analyst
email: fasih178@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: ZulfiqarFasih
github_username:  FasihZ
instagram_username: fasihz
linkedin_username: fasihz
youtube_username: fasihzulfiqar2015

additional_links:
- title: Blog
  icon: fa-brands fa-blogger
  url: https://pakonomist.wordpress.com

# About Section
# about_title: About Me
about_profile_image: https://media.licdn.com/dms/image/D4E03AQGpx43JyXJQ1Q/profile-displayphoto-shrink_400_400/0/1689577305057?e=1697068800&v=beta&t=Saw9AyMCIeNlcXv8GzizJ1D5RmGZsiVg_YkoRE8tnSI
about_content: | # this will include new lines to allow paragraphs
  I’m a ***Client Success Manager at Trademor x Alibaba***, a student, and an aspiring data analyst.   

  Having ***self-studied*** for my secondary education due to financial constraints, I'm a proud autodidact. A ***distinction holder in A-level Economics*** in Pakistan and was awarded a scholarship by Professor Tyler Cowen, Mercatus Center, to pursue Economics.
      
  Aside from academics and work, I'm a big football fan and was part of a club, GSA, for 6 years. Super into travelling and Philosophy, particularly Stoicism and Absurdism. And dogs. I love dogs.

  <i class="fas fa-plane"></i> <mark>Why travelling?</mark> I love to travel because it allows you to be in cultures much different than yours. Plus I love tasting new foods :D

  <i class="fas fa-dumbbell"></i> <mark>Why Powerlifting?</mark> Helps me push myself to new limits. When you have 250 lbs on your back and you squat down, there is always a chance you will fail. Your knees might strain, or worse, break. Conquering that fear is why I love powerlifting.

  <mark>Education</mark>  
  ***Qualification***: BS Econonomics & Mathematics at IBA  
  With a specialization in ***Business Intelligence***.
  
  ***CGPA***: 3.91
  
  The CFO of the ***Animal Welfare Society*** at IBA, Karachi.  

# Experience Section
experience_title: Projects

# Projects Section
projects_title: Personal Projects

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left #top-middle
        #border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title:  Trailer (un)loading autonomous forklift
        link: https://youtu.be/EcnskOHdL_k
        link_text: Video
        # additional_links:
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Autonomous forklift that moves pallets from staging lanes and places them directly into the trailer and viceversa.
        #description: | # this will include new lines to allow paragraphs
        #  Description about the work on/with the project
      - layout: left #top-middle
        #border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Industrial omnidirectional heavy load carrying robot
        #link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        link_text: Link Text
        # additional_links:
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        #   - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #     icon: fab fa-github
        #     url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Omnidirectionat robot that moves large paper rolls from point A to point B.
        #description: | # this will include new lines to allow paragraphs
        #  Description about the work on/with the project
      - layout: left
        #border: weak
        title:  Industrial self-driving forklift
        link: https://youtu.be/QHXtqM1hxqA
        link_text: Video
        #github: 
        quote: >
          Autonomous outrigger type forklift.
        #description: | # this will include new lines to allow paragraphs
      - layout: left
        #border: weak
        title:  GideonBot
        link: https://www.youtube.com/watch?v=dPC0Tclm1Rs
        link_text: Video
        #github: 
        quote: >
          GideonBot solves industrial problems with autonomous mobile robots powered by AI.
        #description: | # this will include new lines to allow paragraphs
      - layout: left
        title:  Household robot assistant
        link: https://www.youtube.com/watch?v=H4-wtJz4IEg
        link_text: Video
        additional_links:
          - title:  Github
            icon: fab fa-github
            url: https://github.com/aeolusbot
        quote: >
          From delivering food to picking up clutter and locating lost items, our robots are always ready to help.
      - layout: left
        title: Continuous casting of long strands of metal
        link: https://www.youtube.com/watch?v=3nW9LyWV72g
        link_text: Video
        quote: >
          Continuous casting is the process where a metal is heated until it liquefies.
        #description: | # this will include new lines to allow paragraphs
        #  Software for the control of manufacturing processes        

#Professional Experience Section
educaton_title: Professional Experience

# Footer
footer_show_references: false

# Slider Settings
slider_settings:
  enabled: true
  loop: true
  auto: true
  speed: 800
  pause: 3000

# Build settings
remote_theme: nbentoneves/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
